#!/bin/bash

# pokemon=$(jq '{name, weight, height, type:.types[].type.name }' data.json)

[ -s data.json ] || { echo "Error: data.json not found or empty"; exit 1; }

name=$(jq -r '.name' data.json | sed -E 's/(.)(.*)/\U\1\L\2/')
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)
type=$(jq -r '.types[].type.name' data.json | sed -E 's/(.)(.*)/\U\1\L\2/' | paste -sd ", ")

formatted_weight=$(awk -v w="$weight" 'BEGIN {printf "%.1f", w / 10}')
formatted_height=$(awk -v h="$height" 'BEGIN {printf "%.1f", h / 10}')


echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

# echo "$pokemon"

#printf %.1f\\n $[${height} / 10]
#echo "${pokemon[0]} is of type ${pokemon[3]}, weighs ${pokemon[1]}kg and is ${pokemon[2]}m tall."
